import type { Metadata } from "next";
import { Inter as FontSans } from "next/font/google";
import "./globals.css";

import { cn } from "@/lib/utils";
import SideNavBar from "@/components/SideNavBar";

const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={cn(
          "h-screen bg-background font-sans antialiased",
          fontSans.variable
        )}
      >
        <header className="h-12 mb-10 bg-slate-500"></header>
        <div className="h-full flex flex-1">
          <SideNavBar />
          <main className="flex-1 p-8">{children}</main>
        </div>
        <footer className="h-20"></footer>
      </body>
    </html>
  );
}
